### ISSUE TITLE
Support ++, --, +=, ? and other good operators

### ISSUE THREAD

**Issue by rockingdice** [hetu-script/hetu-script#17]
Currently, there lacks a bunch of operators that should be implemented. We should support at lease the most useful ones.

**Comment by hythl0day** [comment]
Added in 0.1.0

**Comment by hythl0day** [comment]
I'm not sure what do you mean by ? do you mean null checker or ternary operator?

**Comment by rockingdice** [comment]
With the latest version, it should satisfy most cases. I'll close it then.
