### ISSUE TITLE
Dart function types should be able to bind like external functions and classes

### ISSUE THREAD

**Issue by rockingdice** [hetu-script/hetu-script#18]
There's a case that a dart function require a function type parameter and we want to implement the function inside the script. 
The common case is :
`ListView.builder`

You will need to bind an external function to make a function wrapper for `HTFunction` to make it wrapping with a `Function` with the same signature of the paramter.

We should have a script way to support this kind of type officially.

**Comment by hythl0day** [comment]
In version 0.1.0 added new interpreter function for bind Dart Function Typedef. Example:

In Hetu script:

```dart
fun [DartFunction] add(a: num, b: num): num {
  return a + b
}

fun getFunc {
  return add
}
```

Then when you evaluate this [add] function in Hetu, you will get a native Dart function.

```dart
typedef DartFunction = int Function(int a, int b);

int hetuAdd(DartFunction func) {
  var func = hetu.invoke('getFunc');
  return func(6, 7);
}
```

You have to bind the Dart typedef in [Interpreter.init] before you can use it.

```dart
await hetu.init(externalFunctions: {
  externalFunctionTypedef: {
  'DartFunction': (HTFunction function) {
    return (int a, int b) {
      // must convert the return type here to let dart know its return value type.
      return function.call([a, b]) as int;
    };
  },
});
```

Please check the example/external_function.dart code for more information on this matter.
