### ISSUE TITLE
Support externalFunctions as async

### ISSUE THREAD

**Issue by winterdl** [hetu-script/hetu-script#2]
Hello,

Could you please support async externalFunctions

```
var hetu = await Hetu.init(externalFunctions: {
    'dartHello': (HT_Instance instance, List<dynamic> args) async {
     // await async tasks.....
      return {'dartValue': 'hello'};
    },
```

**Comment by fpv999** [comment]
also 'async' for internal functions might be required. Like when you want to add external method to retrieve HTTP request. 
Would it be possible in the current architecture?

**Comment by fpv999** [comment]
Consider this Hetu script

```
external fun slowExternalMethod

fun handler() {
 print('OK') 
}

fun main {
  print(1)
  slowExternalMethod( handler )
}
```

and this Flutter part:
```

Future<void> slowExternalMethod(List<dynamic> args) async
{
  await Future.delayed(new Duration(seconds:3));
  hetu.eval( '', invokeFunc: args[0].name.toString() ).toString(); 
}

hetu = await Hetu.init(externalFunctions: {
    'slowExternalMethod': (HT_Instance instance, List<dynamic> args) {
      slowExternalMethod(args);
      return 0; 
    },
  });
```

It works for external methods that are doing async operations, 
but it would be cool if we could invoke **HT_Function** directly, 
with the use of its context data, which is inside (without the .name.toString() )

**Comment by fpv999** [comment]
looks like I found a way:

```
Future<void> slowExternalMethod(List<dynamic> args) async
{
  await Future.delayed(new Duration(seconds:3));
  args[0].call(hetu, null, null, []);
}

```

**Comment by fpv999** [comment]
@hythl0day any chance for supporting lambda anonymous function then? ;)

`slowExternalMethod( () { print("OK!") )`

**Comment by winterdl** [comment]
we could using callback pattern like your code to achieve the requirement, I will testing the idea, thank you.

**Comment by winterdl** [comment]
I'm stucking at this issue, my hetu script logic call externalFunctions get data from db or a service, these functions were async function,

hetu script

`var logicData = _externalLogicUser(username)`

but the _externalLogicUser call some async function, then _externalLogicUser also a async function, the engine didnt support it, I could not apply callback in this case.

**Comment by fpv999** [comment]
but your _externalLogicUser should accept second parameter, a reference to the callback method , just as in my example above.

**Comment by winterdl** [comment]
Because I'm waiting for return result from the code:

var res = await hetu.evalf("./test/ht_user.ht",
      invokeFunc: 'main',
      args: [username]);

if (res != null) {....// process value from script return }

if the slowExternalMethod was called, It's will immediate return value 0 to the main thread, I need to lock and wait the async  function return value before return value to main thread.

**Comment by fpv999** [comment]
ok, I understand now. I believe you would need 'await' functionality inside Hetu script for that.

**Comment by hythl0day** [comment]
This is a major functionality, I don't have time to look into how to implement this right now. But I think it definitely should included in the future.

**Comment by winterdl** [comment]
The library meet 90% of my requirements, small and easy too use, I will read to understand the code and waiting for good news. Maybe we need isolate to support async taks. Thank you for your support.

**Comment by fpv999** [comment]
it all depends whether you need to call async methods, or you need to do heavy load calculations (that would require isolate).

**Comment by winterdl** [comment]
I refactoring my code to two states, one is call script and forget, one is listen on all reports message from script, somethings like this:

ht_user.ht
```
proc main(username: String) {
    _onMessage({state: 'running'})
    getUser(username, processData)  // sending callback function
}

fun processData(res: any) { 
    if (abc) {
       _onMessage({state: 'finish', data: newData})
    } else {
      _onMessage({state: 'error', data: newData})
    }
}
```
On flutter site, I dont get the return value from hetu.eval, instead, I use _onMessage function to receiving the state and data of running script.

Thank you.

**Comment by Wetbikeboy2500** [comment]
Since this still seems to be ongoing, I threw together a [gist](https://gist.github.com/Wetbikeboy2500/548e579e2ff222d669b24c1e99ef3dfb) that allows futures to complete and then have a callback with its data being sent to a script function. I just wanted to put this here if anyone finds it useful.

**Comment by zyrouge** [comment]
+1 for this.

**Comment by hythl0day** [comment]
I have added a simple Future wrapper for the script to do things after the Future is completed. However, I don't plan to make users can use async-await, etc. within script or external functions, because that would make everything else unnecessarily async.

The example of the new Future usage in script:

```dart
import 'package:hetu_script/hetu_script.dart';

Future<void> fetch() {
  // Imagine that this function is fetching user info from another service or database.
  return Future.delayed(
      const Duration(seconds: 2), () => print('Hello world after 2 seconds!'));
}

void main() {
  var hetu = Hetu();
  hetu.init(externalFunctions: {'fetch': fetch});
  hetu.eval(r'''
      external fun fetch
      final future = fetch()
      future.then((value) {
        print('future completed!')
      })
  ''', asScript: true);
}
```
