### ISSUE TITLE
Cannot call break in for-in loop

### ISSUE THREAD

**Issue by Wetbikeboy2500** [hetu-script/hetu-script#24]
I am currently using version 0.1.0+2. When I call a break inside of a for-in loop, it throws a `Bad state: no element` error.

Example:
```var hetu = Hetu();
  await hetu.init();
  await hetu.eval(r'''
      fun main {
        let value = ['', 'hello', 'world']
        let item = ''
        for (let val in value) {
          if (val != '') {
            item = val
            break
          }
        }
        print(item)
      }''');

  var hetuValue = hetu.invoke('main');```

**Comment by hythl0day** [comment]
Hi Matt

I will try to recreate it and get back to you as soon as possible.

The version under 1.0 will often be unstable time from time, please forgive me for this.

**Comment by hythl0day** [comment]
BTW, 'for...of' is removed because for supporting break statement, I have to use hard bytecode for 'for...in'. and there's not an easy way to iterate through a Map.values iterable in bytecode.
