### ISSUE TITLE
master分支和develop分支的REPL里result总是null

### ISSUE THREAD

**Issue by mabDc** [hetu-script/hetu-script#26]
`bin/hetu.dart` 55行-60行这里
```dart
          try {
            result = await hetu.eval(input, codeType: CodeType.block);
            if (result != null) print(result);
          } catch (e) {
            print(e);
          }
```

**Comment by hythl0day** [comment]
The repl rules is changed, I didn't change it in the readme.
Now it wont print if it's a  statement, e.g., when you write
```
var a = 4
```
it won't print 4 now. You have to write
```
print(a)
```
to print it.

and the pub version package's reply is broken (it has a bug that didn't await the init)
to use the develop version, you can manually run the script by:
```
dart bin/hetu.dart
```

**Comment by hythl0day** [comment]
Okay, I commited to the develop. So the expression will be printed out correctly
the statement will still return null, however if you type a expression or a symbol, it should be printed out.

**Comment by mabDc** [comment]
thank you
