### ISSUE TITLE
Module Handler Imports

### ISSUE THREAD

**Issue by Wetbikeboy2500** [hetu-script/hetu-script#27]
I am currently using version 0.1.1+1. I am using imports inside my hetu scripts. I started running into an issue where the working directory was not being added to the script imports and was instead adding `.\`. I have tracked down what is going wrong, so I am just gonna dump what I know. 

The current issues is coming from here:
https://github.com/hetu-script/hetu-script/blob/7daace4f49474cdb13b2795035791c744d7e1c77/lib/src/plugin/moduleHandler.dart#L56-L60

I am using `hetu.eval()` which when not given `moduleUniqueKey` doesn't default to null. This causes the `path.dirname(curUniqueKey)` to default to `.` for the path and would never use `workingDirectory`. I did a little hack and passed `bin\\hetu\\.` as the `moduleUniqueKey` for the eval and was able to get the imports to work.

**Comment by hythl0day** [comment]
I fixed this in the master branch, I will update the pub.dev package later with some other fixes.

Please remember if you are using eval and using 'import' statement in the script, the default working directory is setted by your IDE. And I recommend writing your own module handler plugin to deal with files on your specific platform.

**Comment by Wetbikeboy2500** [comment]
Thank you for the advice. Writing my my own module handler is something I didn't realize I could do. It will definitely help. 

Thanks for the quick response and fix.
