### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by aleslanik2** [hetu-script/hetu-script#30]
Hi, your library is awesome and thanks for that!
On Linux and Windows works as a charm.
But on web, dart compiler throws `Unsupported operation: _Namespace `.

Please could you fix it?

Thanks for reply.

**Comment by hythl0day** [comment]
Thanks,
Currently the library need 'dart:io' for reading local file when compiles, if I strip the compiler and just leaves the interpreter, it might be okay to run in browser.
I maybe try this later.
Currently I'm not working on this project, I might return to work several weeks later.

**Comment by rockingdice** [comment]
I think it's still beneficial to support web too. The scripts are strings, so they can be loaded on the fly. If we don't use import, we can load them from server or other sources.

**Comment by aleslanik2** [comment]
Is there other problem. Dart js sdk dont support 64 bit data type (int and double) .

**Comment by hythl0day** [comment]
It needs some fundamental structure change to achieve web support.

I have to rewrite module and context implementation to strip the dart:io dependency. And it needs an outside tool to achieve import without dart:io in the library.

If this is needed for a lot people, I need to make the decision now before it's too late to change this project.

So if any other people are using this library and have thoughts on this issue feel free to share with me.

**Comment by hythl0day** [comment]
Since 0.3.1, hetu script supported web platform.
for file system handling, use another package: hetu_script_dev_tools
for flutter, use: hetu_script_flutter

**Comment by aleslanik2** [comment]
Thanks a lot!! In few days i will try it.

**Comment by aleslanik2** [comment]
Hi unfortunately, when you try to run the script. I get this exception

```
The following HTError object was thrown building FutureBuilder<void>(dirty, state: _FutureBuilderState<void>#28e7b):
  File: hetu:value
Line: 0, Column: 0
Runtime error: extern
Message: Unsupported operation: Int64 accessor not supported by dart2js.
Dart stack trace:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/hetu_script/interpreter/interpreter.dart 242:7                       handleError
packages/hetu_script/interpreter/interpreter.dart 286:9                       evalSource
packages/hetu_script/interpreter/abstract_interpreter.dart 161:20             eval
packages/hetu_script/interpreter/abstract_interpreter.dart 110:9              init
packages/hetu_script/interpreter/interpreter.dart 184:11                      init
```

**Comment by hythl0day** [comment]
> Hi unfortunately, when i try to run the script. I get this exception
> 
> ```
> The following HTError object was thrown building FutureBuilder<void>(dirty, state: _FutureBuilderState<void>#28e7b):
>   File: hetu:value
> Line: 0, Column: 0
> Runtime error: extern
> Message: Unsupported operation: Int64 accessor not supported by dart2js.
> Dart stack trace:
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
> packages/hetu_script/interpreter/interpreter.dart 242:7                       handleError
> packages/hetu_script/interpreter/interpreter.dart 286:9                       evalSource
> packages/hetu_script/interpreter/abstract_interpreter.dart 161:20             eval
> packages/hetu_script/interpreter/abstract_interpreter.dart 110:9              init
> packages/hetu_script/interpreter/interpreter.dart 184:11                      init
> ```

int64 is another issue, but I'm not sure what exact is  the class that

**Comment by hythl0day** [comment]
Maybe because this method?

```dart
  /// Fetch a int64 from the bytes list
  int readInt64() {
    final start = ip;
    ip += 8;
    return bytes.buffer.asByteData().getUint64(start);
  }
```

**Comment by hythl0day** [comment]
Could you check the branch web_fix to see if it works?

I changed the method from int64 into int32 in that branch.

**Comment by aleslanik2** [comment]
IMHO this method has smae issue

```
 /// Fetch a float64 from the bytes list
  double readFloat64() {
    final start = ip;
    ip += 8;
    return bytes.buffer.asByteData().getFloat64(start);
  }
```

**Comment by aleslanik2** [comment]
Flutter for web doesnt support 64bit variable. Only 32bit. This is core of this issue

**Comment by hythl0day** [comment]
Okay I changed both the compiler and bytecode reader, and I tested in chrome (flutter run -d chrome), it seems okay for me to run a example in web now.

**Comment by aleslanik2** [comment]
The problem is little more complicated. 

1.  variable must load as 32bit  (bytecode_reader.dart)
2. variable must stored as 32bit (compiler.dart)

This fork works as a charm for me.

 https://github.com/aleslanik2/hetu-script/commit/044fcdf87da620cc8ccd031e35985cca9f1ddc52

**Comment by aleslanik2** [comment]
But I have no idea what other consequences this may cause.

**Comment by hythl0day** [comment]
Yes I have tried it out myself. And I will merge this change into master branch.

**Comment by hythl0day** [comment]
I have added BigInt class binding in case we need to manipulate bigger integers after we changed it from 64 to 32.

**Comment by aleslanik2** [comment]
Thanks so much for your work!
