### ISSUE TITLE
Eval function context issues

### ISSUE THREAD

**Issue by juh9870** [hetu-script/hetu-script#51]
I was experimenting with eval function, and found a couple of issues with it.
| Name | Value |
| --- | --- |
| **Dart source** | https://pastebin.com/5DreEJsZ |
| **Dart version** | Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64" |
| **hetu_script version** | 0.3.12 |
| **hetu_script_dev_tools version** | 0.0.9 |
I've noticed that `eval` can only work with variables from global scope
```dart
fun local(){
    var meaning;
    eval("meaning = 'hello from a deeper dream!'");
    meaning;
}

local();
```
This will throw an error:
![image](https://user-images.githubusercontent.com/15922601/161547579-9afc505b-7ad9-455e-934d-a21b6bf0fcd5.png)

```dart
var meaning;
fun global(){
    eval("meaning = 'hello from a deeper dream!'");
    meaning;
}

global();
```
But this code runs just fine
![image](https://user-images.githubusercontent.com/15922601/161548203-8d612b55-063e-4719-95b0-9fa01a995ec3.png)

Is this an intended behavior or a bug?

**Comment by hythl0day** [comment]
This is explain in #50.
