### ISSUE TITLE
Eval function return value issue

### ISSUE THREAD

**Issue by juh9870** [hetu-script/hetu-script#52]
I was experimenting with eval function, and found a couple of issues with it.

| Name | Value |
| --- | --- |
| **Dart source** | https://pastebin.com/5DreEJsZ |
| **Dart version** | Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64" |
| **hetu_script version** | 0.3.12 |
| **hetu_script_dev_tools version** | 0.0.9 |

`eval` function returns no value. To be more precise, it retuns value in a very weird form, that can't be read from hetu code.
Examples:
```dart
eval("3");
```
![image](https://user-images.githubusercontent.com/15922601/161549602-6a821325-518d-4e00-9e92-66fbeb9fc8b4.png)
Dart gets returned value just fine, but let's try to assign it to a variable

```dart
var a = eval("3");
a;
```
![image](https://user-images.githubusercontent.com/15922601/161550259-5a45ea2f-34a8-40d6-a6e0-3dd246bb7165.png)
Suddenly, we are now getting null from running this code, weird.

```dart
print('Eval result: ${eval("3")}');
```
![image](https://user-images.githubusercontent.com/15922601/161549969-20d52b5f-8018-475b-b1c1-de33d7faa4aa.png)
Printing it had no success either.

```dart
fun main(){
    eval("3");
}
main();
```
![image](https://user-images.githubusercontent.com/15922601/161550733-391d3f01-2e59-48e1-b96e-034118a225c1.png)
Can't be returned from a function.

But here comes the weird part: I created a custom eval function, that basically is a 1:1 replica to the regular eval function:
```dart
hetu.init(externalFunctions: {
    "my_eval": (HTEntity entity,
        {List<dynamic> positionalArgs = const [],
        Map<String, dynamic> namedArgs = const {},
        List<HTType> typeArgs = const []}) {
      final code = positionalArgs.first as String;
      return hetu.eval(code);
    }
  });
```
Now, when I call following code, it works fine
```dart
external fun my_eval;

var a = my_eval("3");
a;
```dart
![image](https://user-images.githubusercontent.com/15922601/161552245-ebe53200-a1df-4df4-9d4f-8786b9b69ba8.png)
But it doesn't get any further than that
```dart
var a = my_eval("3");
var b = a;
b;
```
![image](https://user-images.githubusercontent.com/15922601/161552370-6f2a5d62-d134-42b5-b287-1967ecc392ed.png)

Hetu script still can't interract with that value in any way. Not even reassign it to another variable

**Comment by hythl0day** [comment]
This is explained in #50.
