### ISSUE TITLE
Interesting observation with Notifier pattern in hetu

### ISSUE THREAD

**Issue by SeanfvdM** [hetu-script/hetu-script#59]
So when evaluating the below sample of the Notifier pattern, the listener is getting ran twice and there is not duplicate listeners.

I don't think this is a big issue, just an interesting observation. 

## Console output from CodePad
![image](https://github.com/hetu-script/hetu-script/assets/36045872/f38e329e-c21f-470a-a82c-8793e97e0459)
 
## Expected Output
![image](https://github.com/hetu-script/hetu-script/assets/36045872/9e337b60-c7c5-4155-b02e-3fbb46079b8a)

## Sample code
```hetuscript
type VoidCallback = () -> void

abstract class ChangeNotifier {
  var _listeners: List<VoidCallback> = []

  fun addListener(listener: VoidCallback) {
    _listeners.add(listener);
  }

  fun removeListener(listener: VoidCallback) {
    _listeners.remove(listener);
  }

  fun notifyListeners() {
    for (var listener in _listeners) {
      listener();
    }
  }
}

class Listenable extends ChangeNotifier {
  var _name = 'Jeff'
  
  get name -> str {
    return _name
  }
  
  set name(new_name: str) {
    //This is a workaround to double set calls
    //if (_name != new_name) {
      _name = new_name
      notifyListeners()
    //}
  }
}

fun main() {
  var l = Listenable()
  print(l.name)
  
  l.addListener(() {
    print(l.name)
  })
  
  l.name = 'Jerry'
  
  l.name = 'Bob'
}

main()
```

**Comment by hythl0day** [comment]
Hi, I have checked the code, this is a bug related to the setter of a instance. I have pushed a new commit to the main repo and should fix this. Thanks!

**Comment by hythl0day** [comment]
The lib is okay now, however I have to recompile the web codepad to update it with the latest version.
