### ISSUE TITLE
IntelliJ/AndroidStudio language plugin

### ISSUE THREAD

**Issue by nikitafedorov008** [hetu-script/hetu-script#61]
please add plugin support for IntelliJ, it will be useful for those who develop in Android Studio or IntelliJ IDEA instead of VS Code

**Comment by hythl0day** [comment]
I will try to solve the issues of this project if any one find any. But sorry I do not have energy anymore for any new feature request for this project. I have not touched it almost for a year now.
The development of language plugin is very complex, I do not own any version of IntelliJ and I am not familliar with this IDE. From the little understanding I have right now, to make language plugin for it require one to write a parser in Java. This is clearly not easy. So anyway, I am sorry but I cannot help you.

**Comment by nikitafedorov008** [comment]
I created a HetuScript plugin for the JetBrains IDEs, it has basic syntax highlighting and configuration launching
https://github.com/nikitafedorov008/hetu-script-intellij-plugin
